/* generated by gensort */
package tests

import (
	"math/rand"
	"sync"
)

func cmpQuickSort(_xs []int) {
	_partition := func(_xs []int) (_low, _high []int) {
		var (
			_chosen = rand.Intn(len(_xs))
			y       = _xs[_chosen]
		)

		_i, _j := 0, 0
		for _k, x := range _xs {

			_cmp := x - y
			if _cmp < 0 {

				_xs[_k] = _xs[_j]
				_xs[_j] = _xs[_i]
				_xs[_i] = x
				_i++
				_j++

			} else if _cmp == 0 {

				_xs[_k] = _xs[_j]
				_xs[_j] = x
				_j++
			}
		}

		return _xs[:_i], _xs[_j:]
	}

	const threshold = 1000
	var wg sync.WaitGroup
	var cmpQuickSort func([]int)
	cmpQuickSort = func(xs []int) {
	init:
		if len(xs) <= 1 {
			return
		}

		low, high := _partition(xs)

		var short, long []int
		if len(low) < len(high) {
			short, long = low, high
		} else {
			short, long = high, low
		}

		if len(short) > threshold {
			short := short
			wg.Add(1)
			go func() {
				cmpQuickSort(short)
				wg.Done()
			}()
		} else {
			cmpQuickSort(short)
		}
		xs = long
		goto init
	}

	cmpQuickSort(_xs)
	wg.Wait()
}
